"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const classes_1 = require("./classes");
const guildrank_1 = require("./guildrank");
/**
 * Returns a `PlayerData` object with default properties.
 * @deprecated Prefer `const data = {} as PlayerData;` to create new `PlayerData` objects.
 */
function getDefaultPlayerData() {
    return {
        objectId: 0,
        worldPos: undefined,
        name: undefined,
        level: 0,
        exp: 0,
        currentFame: 0,
        stars: 0,
        accountId: undefined,
        accountFame: 0,
        gold: 0,
        class: classes_1.Classes.Wizard,
        className: "Wizard",
        nameChosen: false,
        guildName: undefined,
        guildRank: guildrank_1.GuildRank.NoRank,
        maxHP: 0,
        maxHPBoost: 0,
        maxMP: 0,
        maxMPBoost: 0,
        hp: 0,
        mp: 0,
        atk: 0,
        atkBoost: 0,
        def: 0,
        defBoost: 0,
        spd: 0,
        spdBoost: 0,
        dex: 0,
        dexBoost: 0,
        wis: 0,
        wisBoost: 0,
        vit: 0,
        vitBoost: 0,
        condition: 0,
        hpPots: 0,
        mpPots: 0,
        hasBackpack: false,
        inventory: new Array(20).fill(-1),
        server: undefined,
        size: 0,
        nextLevelExp: 0,
        clothingDye: 0,
        accessoryDye: 0,
        nextClassQuestFame: 0,
        legendaryRank: 0,
        xpBoosted: false,
        xpBoostTime: 0,
        texture: 0,
        fortuneTokens: 0,
        projSpeedMult: 0,
        projLifeMult: 0,
        exaltedHP: 0,
        exaltedMP: 0,
        exaltedAtt: 0,
        exaltedDef: 0,
        exaltedSpd: 0,
        exaltedDex: 0,
        exaltedVit: 0,
        exaltedWis: 0,
        potionOneType: 0,
        potionOneAmount: 0,
        potionTwoType: 0,
        potionTwoAmount: 0,
        potionThreeType: 0,
        potionThreeAmount: 0,
        potionBelt: false,
        forgefire: 0
    };
}
exports.getDefaultPlayerData = getDefaultPlayerData;
